version: '3'
services:
    vue:
        build:
            context: ./docker/vue
        container_name: myapp-vue
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - .:/db
        working_dir: /app
        tty: true
        # command: sh -c "cd assets && npm install && npm run serve"

    go:
        build:
            context: ./docker/go
        container_name: myapp-go
        ports:
            - 8082:8082
        volumes:
            - .:/go/src
        working_dir: /go/src/app
        tty: true
    mysql:
        image: mysql:8.0
        volumes:
        - sample-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sample
        ports:
            - 3307:3306
volumes:
    sample-mysql-data: